language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.3
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer install
script:
  - vendor/bin/phpunit
before_deploy:
  - eval $(ssh-agent -s)
  - openssl aes-256-cbc -K $encrypted_0d40149d71bc_key -iv $encrypted_0d40149d71bc_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo ${SSH_HOST_KEY} >> ~/.ssh/known_hosts
deploy:
  - provider: script
    script: ssh -o ForwardAgent=yes www-data@opendata02.nine.ch "cd /home/www-data/transport.opendata.ch && git pull --rebase --stat && /home/www-data/bin/composer install --no-dev --no-interaction --no-progress --optimize-autoloader"
    on:
      branch: master
      php: 7.0
